FROM python:3.10-slim

WORKDIR /app

COPY requirements.txt .

RUN pip install --no-cache-dir -r requirements.txt

RUN rm requirements.txt

COPY ./auth_service /app

CMD ["celery", "-A", "auth_service.celery", "worker", "--loglevel=info"]